### ISSUE TITLE
tab错误

### ISSUE THREAD

**Issue by huaxianmfs** [acezx-programer/H-SR-cutscene-extractor#5]
demux.py文件中，第93行，开头是两格省略号缩进，需要更改为单个箭头缩进（在使用notepad++打开时），
另外还需要在目录中添加 output/converted 文件夹，才能正常运行，希望进行修正。

**Comment by acezx-programer** [comment]
reinstall PycriUSM

**Comment by huaxianmfs** [comment]
PycriUSM仓库中的，cri_usm_demuxer/demux.py 第93行是正确的，但是在这个仓库中的usm/demux.py 第93行缩进有问题，我重新下载后问题仍然存在

**Comment by BUnipendix** [comment]
应该是我之前提交更新的时候直接从我的项目库里复制部分修改过的代码（因为这个仓库的版本和我的有点不太一样）造成的问题
