### ISSUE TITLE
TabError: still a problem.

### ISSUE THREAD

**Issue by NewBundle** [acezx-programer/H-SR-cutscene-extractor#6]
Hey there, grabbed this and followed your directions, but I have the same problem as [huaxianmfs](https://github.com/huaxianmfs) - it throws up "TabError: inconsistent use of tabs and spaces in indentation".   I tried what you said to them, re-installing pyrciusm, no love.

It specifies line 93, so if I correct the inconsistency by replacing spaces with tabs, I get "IndentationError: expected an indented block after function definition on line 93".

If I indent the block after 93, I get what [moux23333](https://github.com/moux23333) gets: "ImportError: DLL load failed while importing decrypt: %1 is not a valid Win32 application."

As per your instruction for Moux23333's problem, re-downloading pyrciusm and copying the decrypt over doesn't resolve it.

Going further down the rabbit hole, when this is all fixed manually, and the extractor actually runs, it inevitably comes back with "NameError: name 'chunk_filter_config' is not defined".  And that's about as far as I can get.

**Comment by acezx-programer** [comment]
I've been trying to fix all issues and it seems one leads to the other 0-0. currently, I am busy with personal stuff, so I am unable to fix this as of right now. with my current state i don't think this project is going to get anywhere near finished soon and i am sorry for the issue.

**Comment by NewBundle** [comment]
Understood - it's almost like people have lives! 

I was able to find someone on Bilibili who had used your tool in the past to pull down all the cutscenes, so if nothing else, your tool gave me what I needed indirectly.

**Comment by huaxianmfs** [comment]
你可能错误的使用了PyCriUsm构建的文件，需要其生成在根目录的.pyd文件。
我记得我在解决了tab错误之后也遇到过类似的问题，但是过太久，忘了是怎么解决的，所以我重新操作了一遍。
也有可能是我之前已经解决了问题，是这次的失误导致的
希望对你有所帮助~
以下是机翻（Here are the flips）
You may be using a file built by PyCriUsm incorrectly and need to generate a.pyd file in the root directory.
I remember running into a similar problem after fixing the tab error, but after too much time, I forgot how to fix it, so I did it all over again.
Or it could be that I have solved the problem before, and it is this mistake that leads to it
Hope to help you ~

**Comment by LumonosityMSU** [comment]
I get the same error. Unsure what I'm doing wrong, has anyone found a fix?

**Comment by acezx-programer** [comment]
Iridium-SR is a tool like a packet sniffer(notice im using "like"), because it is not a exactly a packet sniffer. this tool was made by tamilpp25(an acquaintance of mine) and was contributed many times since. its purpose was to sniff protos(hoyo game uses googles "proto"). one of those proto contains data that has a value named key.
